<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Attachment;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * The Final Approval Request email — reuses the same generic subject/body
 * wrapper view every other announcement email in this app uses
 * (`emails.checklist-signatory-announcement`), but unlike those, always
 * carries the Clearance Form as a real attachment: the PDF always, plus a
 * rasterized PNG "screenshot" of it when one could be generated (see
 * `ClearanceFormController::screenshotPngFromBytes()` — requires Imagick +
 * Ghostscript; its absence degrades to PDF-only rather than failing the
 * whole send).
 *
 * `ShouldQueue` — sent in the background instead of blocking the request;
 * see `ChecklistSignatoryAnnouncementMail`'s own matching comment for why.
 * The PDF/PNG bytes are already generated by the time this Mailable is
 * constructed (that work isn't deferred by queueing) — only the SMTP send
 * itself moves to the background.
 */
class FinalApprovalRequestMail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    // Stored base64-encoded, not raw — this Mailable is queued (ShouldQueue),
    // and Laravel JSON-encodes its public properties to persist the job in
    // the `jobs` table. Raw PDF/PNG bytes aren't valid UTF-8, which makes
    // that JSON encoding fail with "Malformed UTF-8 characters". See
    // attachments() below, which decodes it back.
    public string $pdfBytes;

    public ?string $pngBytes;

    public function __construct(
        public string $emailSubject,
        public string $emailBody,
        string $pdfBytes,
        public string $offboardeeName,
        ?string $pngBytes = null,
    ) {
        $this->pdfBytes = base64_encode($pdfBytes);
        $this->pngBytes = $pngBytes !== null ? base64_encode($pngBytes) : null;
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: $this->emailSubject,
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.checklist-signatory-announcement',
            with: [
                'emailSubject' => $this->emailSubject,
                'emailBody' => $this->emailBody,
            ],
        );
    }

    /**
     * @return array<int, Attachment>
     */
    public function attachments(): array
    {
        $attachments = [
            Attachment::fromData(fn () => base64_decode($this->pdfBytes), 'Clearance Form - ' . $this->offboardeeName . '.pdf')
                ->withMime('application/pdf'),
        ];

        if ($this->pngBytes !== null) {
            $attachments[] = Attachment::fromData(fn () => base64_decode($this->pngBytes), 'Clearance Form - ' . $this->offboardeeName . '.png')
                ->withMime('image/png');
        }

        return $attachments;
    }
}
